import { StyleSheet } from 'react-native';
import { colors, fonts } from './theme';
export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  loading: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    backgroundColor: colors.background,
  },
  headerBorder: { borderBottomWidth: 1, borderColor: colors.line },
  header: {
    width: '100%',
    maxWidth: 1224,
    alignSelf: 'center',
    height: 86,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 32,
    gap: 44,
  },
  brand: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  brandMark: { position: 'relative', marginTop: 3 },
  brandDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: colors.rust,
    position: 'absolute',
    bottom: 4,
    right: 4,
  },
  logo: { fontFamily: fonts.title, fontSize: 31, lineHeight: 42, letterSpacing: -1.4 },
  navigation: { flexDirection: 'row', gap: 26, flex: 1 },
  navItem: { flexDirection: 'row', alignItems: 'center', gap: 7, minHeight: 44 },
  navText: { fontFamily: fonts.bold, fontSize: 12 },
  headerActions: { marginLeft: 'auto', flexDirection: 'row', gap: 9 },
  iconButton: {
    minWidth: 40,
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  page: {
    width: '100%',
    maxWidth: 1180,
    alignSelf: 'center',
    paddingHorizontal: 32,
    paddingTop: 32,
    paddingBottom: 20,
  },
  breadcrumb: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 10 },
  inline: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  pill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: colors.greenLight,
    paddingHorizontal: 9,
    paddingVertical: 3,
    borderRadius: 12,
  },
  pillText: { fontSize: 10, lineHeight: 16, color: '#687855', fontFamily: fonts.medium },
  tinyDot: { width: 5, height: 5, borderRadius: 3 },
  titleRow: { flexDirection: 'row', gap: 20, alignItems: 'center', marginBottom: 26 },
  largeTitle: { fontFamily: fonts.title, fontSize: 46, lineHeight: 59, letterSpacing: -1.4 },
  subtitle: { fontSize: 13, color: colors.secondary, lineHeight: 22, marginTop: 5 },
  stamp: {
    width: 89,
    height: 89,
    borderRadius: 45,
    borderColor: '#BC8C7099',
    borderWidth: 1.5,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    marginRight: 13,
    transform: [{ rotate: '10deg' }],
  },
  stampText: {
    color: colors.rust,
    fontSize: 8,
    fontFamily: fonts.bold,
    letterSpacing: 1.4,
    lineHeight: 15,
  },
  stampNumber: { color: colors.rust, fontFamily: fonts.title, fontSize: 15, lineHeight: 19 },
  welcome: {
    borderWidth: 1,
    borderColor: '#DDDBC6',
    backgroundColor: '#EEEDDD',
    borderRadius: 8,
    paddingHorizontal: 15,
    paddingVertical: 12,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 9,
    marginBottom: 23,
  },
  gameColumns: { flexDirection: 'row', gap: 30, alignItems: 'flex-start' },
  boardColumn: { flex: 1.18, minWidth: 0 },
  notebookColumn: { flex: 1, minWidth: 0, marginTop: 36 },
  boardMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  time: {
    fontSize: 11,
    fontFamily: fonts.medium,
    color: colors.secondary,
    fontVariant: ['tabular-nums'],
  },
  trayHeader: {
    marginTop: 21,
    marginBottom: 9,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 5,
  },
  peopleTray: {
    flexDirection: 'row',
    flexGrow: 1,
    alignItems: 'flex-start',
    gap: 3,
    justifyContent: 'space-between',
    paddingBottom: 4,
  },
  person: {
    flex: 1,
    minWidth: 50,
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 1,
    gap: 3,
    borderWidth: 1,
    borderColor: 'transparent',
    borderRadius: 8,
  },
  personSelected: { backgroundColor: colors.greenLight, borderColor: '#90A180' },
  personName: { fontSize: 10, color: colors.secondary, lineHeight: 15 },
  placedBadge: {
    height: 13,
    width: 13,
    borderRadius: 7,
    backgroundColor: colors.green,
    position: 'absolute',
    right: 0,
    bottom: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.paper,
  },
  tools: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 17,
    borderTopWidth: 1,
    borderColor: colors.line,
    paddingTop: 16,
  },
  tool: {
    width: 51,
    minHeight: 47,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    borderRadius: 7,
  },
  toolLabel: { fontSize: 10, lineHeight: 14 },
  toolDivider: { height: 27, width: 1, backgroundColor: colors.line, marginHorizontal: 5 },
  tapTip: { textAlign: 'center', color: colors.muted, fontSize: 10, lineHeight: 17, marginTop: 12 },
  feedback: {
    marginTop: 12,
    backgroundColor: colors.greenLight,
    borderWidth: 1,
    borderColor: '#D4DCC8',
    borderRadius: 8,
    padding: 12,
  },
  alert: { padding: 14, marginBottom: 15, borderRadius: 8, backgroundColor: colors.rustLight },
  gentleNote: { marginTop: 19, flexDirection: 'row', gap: 9, paddingHorizontal: 12 },
  gentleNoteText: { flex: 1, fontSize: 11, lineHeight: 18, color: colors.muted },
  footer: {
    marginTop: 38,
    paddingTop: 19,
    borderTopWidth: 1,
    borderColor: colors.line,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  footerText: { color: colors.muted, fontSize: 10 },
  libraryHero: { paddingTop: 18, paddingBottom: 35 },
  heroStats: { flexDirection: 'row', alignItems: 'center', gap: 7, marginTop: 20 },
  caseGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 18 },
  caseCard: {
    minWidth: 0,
    padding: 20,
    borderRadius: 12,
    borderColor: colors.line,
    borderWidth: 1,
    backgroundColor: colors.paper,
    boxShadow: '0 3px 0 #DEDCCC55',
  },
  caseMeta: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  caseTitle: { fontFamily: fonts.title, fontSize: 25, lineHeight: 33, marginTop: 21 },
  caseDescription: {
    fontSize: 12,
    color: colors.secondary,
    lineHeight: 20,
    marginTop: 8,
    minHeight: 40,
  },
  caseBottom: {
    borderTopWidth: 1,
    borderColor: colors.line,
    marginTop: 23,
    paddingTop: 17,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 12,
  },
  libraryNote: {
    marginTop: 30,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 10,
    padding: 22,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 16,
  },
  helpRow: { flexDirection: 'row', gap: 14, marginBottom: 23 },
  helpNumber: { fontFamily: fonts.title, fontSize: 25, lineHeight: 30, color: colors.rust },
  helpTitle: { fontFamily: fonts.bold, fontSize: 14, lineHeight: 23 },
  helpText: { fontSize: 12, color: colors.secondary, lineHeight: 21, marginTop: 4 },
  modalText: { fontSize: 14, lineHeight: 25, color: colors.secondary, marginBottom: 20 },
  briefFacts: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 20,
    borderTopWidth: 1,
    borderColor: colors.line,
    marginTop: 24,
    marginBottom: 7,
  },
  pauseTime: {
    textAlign: 'center',
    fontFamily: fonts.title,
    fontSize: 44,
    lineHeight: 60,
    marginBottom: 25,
  },
  hintIcon: {
    alignSelf: 'center',
    padding: 20,
    borderRadius: 50,
    backgroundColor: colors.rustLight,
    marginBottom: 23,
  },
  hintCount: { fontSize: 11, color: colors.muted, textAlign: 'center', marginBottom: 18 },
  settingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 20,
    paddingVertical: 18,
    borderBottomWidth: 1,
    borderColor: colors.line,
  },
  accusationGrid: {
    flexDirection: 'row',
    justifyContent: 'center',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 22,
  },
  accusationPerson: {
    width: '30%',
    minWidth: 82,
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 12,
  },
  solutionPortrait: { alignItems: 'center', gap: 15, marginBottom: 24 },
  solvedStamp: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    backgroundColor: colors.greenLight,
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 7,
  },
  results: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 26,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: colors.line,
  },
  resultValue: { fontFamily: fonts.title, fontSize: 28, lineHeight: 38 },
  notebookSummary: { alignItems: 'center', gap: 6, paddingVertical: 13, paddingBottom: 28 },
  recordRow: {
    paddingVertical: 19,
    flexDirection: 'row',
    gap: 15,
    alignItems: 'center',
    borderTopWidth: 1,
    borderColor: colors.line,
  },
});
