import { FurnitureKind, Person } from '../../src/game/types';

export const TITLES = [
  'A Very Quiet Evening',
  'The Missing Place Setting',
  'Death before Dessert',
  'A Knock at Dusk',
  'The Empty Rocking Chair',
  'Tea with a Stranger',
  'The Unopened Gift',
  'A Toast Too Many',
  'The Silent Gardener',
  'The Guest Who Stayed',
  'An Inheritance of Secrets',
  'The Last Houseguest',
  'A Letter in the Lilacs',
  'A Bitter Cup',
  'Footsteps in the Attic',
  'The Disappearing Host',
  'The Broken Music Box',
  'An Orchid for Eleanor',
  'The Clockmaker’s Visit',
  'The Twentieth Invitation',
  'The Last Encore',
  'A Seat in the Stalls',
  'The Understudy’s Secret',
  'Behind the Velvet Curtain',
  'The Silent Violin',
  'An Unfinished Waltz',
  'The Patron’s Last Bow',
  'Applause at Midnight',
  'The Empty Dressing Room',
  'The Conductor’s Note',
  'The Counterfeit Alibi',
  'The Auctioneer’s Secret',
  'Dust on the Decanter',
  'The Portrait in the Hall',
  'A Bid Too Far',
  'The Silver Locket',
  'A Collector’s Obsession',
  'The Unclaimed Parcel',
  'The Ninth Impression',
  'The Clock Strikes Twice',
  'Murder on the Marigold',
  'The Passenger in Grey',
  'No Return Ticket',
  'The Empty Sleeper',
  'The Porter’s Last Round',
  'A Name on the Manifest',
  'The Lost Platform',
  'The Luggage Tag',
  'Departure at Dawn',
  'The Final Connection',
  'The Lighthouse Keeper',
  'A Letter from the Coast',
  'Low Tide at Blackwater',
  'The Captain’s Supper',
  'A Lantern in the Fog',
  'The Pearl in the Pocket',
  'An Unsent Postcard',
  'The Guest at Number Nine',
  'The Sound of the Buoy',
  'The Last Safe Harbour',
  'The Gilded Invitation',
  'The Founder’s Dinner',
  'The Seventh Toast',
  'The Locked Conservatory',
  'The Orchid Society',
  'A Debt of Honour',
  'The Ambassador’s Guest',
  'The Watch in the Fountain',
  'A Toast to Yesterday',
  'The Secret Beneficiary',
  'The Archivist’s Silence',
  'A Page Out of Place',
  'The Last Catalogue',
  'The Ink That Would Not Dry',
  'A Footnote to Murder',
  'The Missing Folio',
  'The Curator’s Appointment',
  'The Photograph in the File',
  'The Unfinished Index',
  'The Sealed Collection',
  'The Blackthorn Affair',
  'A Meeting without Minutes',
  'The Witness at the Window',
  'The Other Invitation',
  'The Ninth Signature',
  'A Shadow in the Gallery',
  'The Patron behind the Portrait',
  'The Circle of Trust',
  'The Incomplete Confession',
  'An Alibi for Everyone',
  'The Inspector’s Invitation',
  'The Last Unanswered Letter',
  'The House of Nine Secrets',
  'A Familiar Stranger',
  'The Night of the Reunion',
  'The Witness Who Remembered',
  'An Appointment with Yesterday',
  'The Final Piece of Evidence',
  'The Penultimate Guest',
  'The Hundredth Case',
];

// Narrative atmosphere only; the typed statements supply all positional evidence.
export const HOOKS = [
  'A quiet evening at the manor has come to an abrupt end.',
  'The supper table was laid for one more guest than anyone remembers inviting.',
  'The pudding is untouched, and nobody is asking for a second helping.',
  'A knock at the door interrupted the gathering just as the daylight faded.',
  'The rocking chair by the hearth stands empty for the first time in years.',
  'Nobody can agree who invited the stranger to afternoon tea.',
  'A beautifully wrapped gift remains unopened after the celebration.',
  'The guests remember every toast, but would prefer to forget the last one.',
  'The gardener brought troubling news inside with the evening flowers.',
  'One guest postponed their departure, and the household may never know why.',
  'The reading of a will has left the house party with rather less to celebrate.',
  'The weekend guests were packing when a discovery stopped every departure.',
  'A letter caught among the lilacs has brought an old quarrel back into the house.',
  'A familiar tea service was brought out for an uncomfortable reunion.',
  'The conversation stopped when footsteps sounded above the drawing room.',
  'The host missed their own farewell toast, sending the guests in search of an explanation.',
  'A broken music box has revived a family story that was supposed to stay forgotten.',
  'A tribute to Eleanor has brought her former friends together under one roof.',
  'The clockmaker arrived to mend a timepiece and found a household counting its secrets.',
  'Nineteen invitations were expected. The twentieth arrived without a signature.',
  'The company has gathered after the final curtain.',
  'An unfamiliar name on a reserved seat has unsettled the theatre company.',
  'The understudy was ready for a debut, but the evening took an unexpected turn.',
  'A private argument behind the curtain has become the talk of the theatre.',
  'A violin case was delivered without its owner before the evening rehearsal.',
  'The musicians stopped midway through a waltz that nobody wants to finish.',
  'The theatre’s patron promised an announcement after the performance.',
  'The midnight applause faded into a silence the company cannot explain.',
  'A name has been removed from a dressing-room door before the end of the run.',
  'A note in the conductor’s score has revived an old disagreement.',
  'A disputed provenance has turned a private auction into a public embarrassment.',
  'The auctioneer’s sealed envelope was meant to be opened after the sale.',
  'An old decanter has brought two rival collectors back into the same building.',
  'A familiar face in an unfamiliar portrait has drawn unwelcome attention.',
  'The final bid was far beyond the estimate, and someone demanded an explanation.',
  'A silver locket from an unnamed estate has attracted an unexpectedly personal dispute.',
  'A collector insisted that one particular lot must never leave the premises.',
  'A parcel arrived before the viewing, but every guest denies ordering it.',
  'An engraving advertised as unique has a ninth impression nobody can account for.',
  'The sale of a clock has reopened a quarrel over its previous owner.',
  'The evening train is carrying more secrets than passengers expected.',
  'A passenger in grey was recognised by someone who wished they had stayed a stranger.',
  'An unused return ticket has become the most poignant item in a traveller’s luggage.',
  'A sleeper berth was prepared for a passenger who never settled down for the night.',
  'The porter’s final round interrupted a conversation nobody will repeat.',
  'A correction on the passenger manifest has drawn several conflicting explanations.',
  'An unexpected change of platform brought old acquaintances onto the same service.',
  'A luggage tag bears the name of someone the passengers hoped never to meet again.',
  'The dawn departure has been delayed while the conductor calls for a detective.',
  'The last connection of the evening has left the passengers with nowhere to go.',
  'The lighthouse keeper came ashore with a story the dinner guests found hard to believe.',
  'A letter from the coast arrived just before the household sat down to supper.',
  'Low tide has exposed something that brought an anxious gathering to the lodge.',
  'A retired captain invited a small company to revisit the voyage that made their fortunes.',
  'A lantern appeared in the fog before an unexpected visitor reached the lodge.',
  'A single pearl has revived a dispute about a necklace thought lost at sea.',
  'An unsent postcard has turned a holiday recollection into an uncomfortable conversation.',
  'The guest registered in room nine arrived with a name nobody quite believed.',
  'The distant buoy sounded through a supper that grew steadily more strained.',
  'The lodge offered shelter from a storm, but its guests have found little peace.',
  'A gilded invitation brought several former members back to the club.',
  'The founder’s annual dinner was interrupted before the traditional speech.',
  'The seventh toast mentioned a name that changed the mood around the table.',
  'A dispute over the conservatory’s missing key has overshadowed a club gathering.',
  'The orchid society’s private reception has taken an unwelcome turn.',
  'An old debt was called in during what should have been a friendly dinner.',
  'The ambassador brought a guest whose past made several members uneasy.',
  'A watch recovered from the fountain has prompted a round of careful questions.',
  'A nostalgic toast has reminded the members of a promise left unfulfilled.',
  'An unexpected beneficiary was announced at the end of a charitable reception.',
  'The archivist asked for a private meeting and left a catalogue open on the desk.',
  'A page filed in the wrong collection has brought a small group to the archive.',
  'The final catalogue includes an entry the collection’s owner wanted removed.',
  'Fresh ink on an old document has caused a heated discussion among the visitors.',
  'A disputed footnote has turned a scholarly gathering into a personal confrontation.',
  'A missing folio was the reason for the meeting, but the investigation has grown larger.',
  'The curator scheduled an appointment outside the archive’s usual visiting hours.',
  'A photograph tucked into a file has connected people who claimed never to have met.',
  'An unfinished index points to a collection nobody was willing to discuss openly.',
  'A sealed collection was opened for the first time in decades before the visitors arrived.',
  'The Blackthorn family has invited a few acquaintances to settle an old matter.',
  'A private meeting was arranged on the understanding that no minutes would be kept.',
  'A visitor recognised someone through a window before joining the gathering.',
  'Two versions of the same invitation have brought very different expectations to dinner.',
  'The ninth signature on an old agreement has become the evening’s uncomfortable subject.',
  'A missing portrait has left a pale rectangle on the wall and a room full of questions.',
  'A portrait’s benefactor has returned to discuss a promise made many years ago.',
  'A close circle of friends has gathered to decide whether an old confidence should be broken.',
  'An unfinished confession was found among papers brought to a private meeting.',
  'Everyone arrived prepared to explain themselves, though nobody expected a detective.',
  'An invitation addressed to an inspector arrived before anyone knew a crime would need solving.',
  'The last of a long correspondence has been returned without an answer.',
  'Nine old secrets have brought a carefully chosen company back to the estate.',
  'The newest guest seems familiar to everyone, but for very different reasons.',
  'A reunion dinner has reopened the conversation that ended their last gathering.',
  'One guest has finally remembered a detail the others hoped was forgotten.',
  'An appointment made years ago has brought its participants back on the promised evening.',
  'A final piece of evidence was due to be revealed to the assembled guests.',
  'The penultimate guest arrived carrying a message intended for the last.',
  'One last invitation. One final gathering. A hundredth mystery for the detective’s notebook.',
];

export const SETTINGS = [
  {
    location: 'Hawthorn House',
    rooms: ['Study', 'Conservatory', 'Parlour', 'Kitchen', 'Gallery', 'Library'],
    hook: 'A family gathering has ended with an empty chair and a room full of careful recollections.',
    detail: 'The supper plates are still on the table.',
  },
  {
    location: 'Rosemere Hall',
    rooms: ['Drawing room', 'Kitchen', 'Library', 'Garden room', 'Music room', 'Studio'],
    hook: 'An unexpected visitor has unsettled a weekend house party.',
    detail: 'An invitation lies folded beside an unfinished cup of tea.',
  },
  {
    location: 'The Bellweather Theatre',
    rooms: ['Music room', 'Green room', 'Gallery', 'Rehearsal room', 'Costume room', 'Lounge'],
    hook: 'A private performance has stopped before the final note.',
    detail: 'The audience is waiting for an encore that will never come.',
  },
  {
    location: 'Whitlock Auction Rooms',
    rooms: ['Gallery', 'Office', 'Viewing room', 'Restoration room', 'Storeroom', 'Library'],
    hook: 'An exclusive auction has become an investigation.',
    detail: 'Every guest remembers the last lot, and every guest has a reason to be here.',
  },
  {
    location: 'The Marigold Express',
    rooms: ['Sleeper cabin', 'Dining car', 'Corridor', 'Luggage room', 'Lounge', 'Observation car'],
    hook: 'The evening express has stopped between stations.',
    detail: 'A conductor has collected the tickets, but one passenger will travel no further.',
  },
  {
    location: 'Blackwater Lodge',
    rooms: ['Map room', 'Dining room', 'Sunroom', 'Study', 'Library', 'Reception'],
    hook: 'Fog has cut a coastal retreat off from the village.',
    detail: 'The lighthouse is visible through the mist; help will have to wait until morning.',
  },
  {
    location: 'The Gilded Club',
    rooms: ['Dining room', 'Library', 'Conservatory', 'Card room', 'Lounge', 'Gallery'],
    hook: 'A members-only dinner has brought old debts back to the table.',
    detail: 'Outside, the rain has washed the gravel drive clean.',
  },
  {
    location: 'The Ashcombe Archive',
    rooms: ['Reading room', 'Archive', 'Office', 'Exhibit room', 'Restoration room', 'Study'],
    hook: 'An appointment in the private collection has ended in silence.',
    detail: 'The catalogue is open, but the most important story is in the witnesses’ positions.',
  },
  {
    location: 'Blackthorn Manor',
    rooms: ['Portrait gallery', 'Study', 'Library', 'Dining room', 'Conservatory', 'Music room'],
    hook: 'An anonymous invitation has brought a circle of acquaintances back together.',
    detail: 'Their shared history is complicated. Their statements about the scene are precise.',
  },
  {
    location: 'The Nine Elms Estate',
    rooms: ['Library', 'Dining room', 'Drawing room', 'Study', 'Conservatory', 'Gallery'],
    hook: 'The final gathering of the season has become the detective’s most demanding assignment.',
    detail: 'Every surviving guest has given a statement, and every position will matter.',
  },
];

export const CAST: [string, string, Person['style']][] = [
  ['Alice', 'The author', 'bob'],
  ['Basil', 'The solicitor', 'hat'],
  ['Clara', 'The artist', 'curls'],
  ['Dorian', 'The architect', 'glasses'],
  ['Edith', 'The collector', 'bun'],
  ['Frances', 'The botanist', 'bob'],
  ['Gideon', 'The chef', 'moustache'],
  ['Hazel', 'The journalist', 'curls'],
  ['Ida', 'The curator', 'glasses'],
  ['Jasper', 'The musician', 'hat'],
  ['Kit', 'The photographer', 'bob'],
  ['Lucian', 'The financier', 'moustache'],
  ['Mae', 'The historian', 'bun'],
  ['Neville', 'The jeweller', 'glasses'],
  ['Opal', 'The florist', 'curls'],
  ['Percy', 'The secretary', 'hat'],
  ['Quinn', 'The actor', 'bob'],
  ['Ruth', 'The traveller', 'bun'],
  ['Sebastian', 'The dealer', 'moustache'],
  ['Tessa', 'The designer', 'curls'],
  ['Ursula', 'The patron', 'bun'],
  ['Vincent', 'The doctor', 'glasses'],
  ['Willa', 'The singer', 'bob'],
  ['Zachary', 'The steward', 'hat'],
];
export const OBJECTS: [FurnitureKind, string][] = [
  ['desk', 'Writing desk'],
  ['books', 'Bookcase'],
  ['plant', 'Potted palm'],
  ['globe', 'Globe'],
  ['sofa', 'Sofa'],
  ['table', 'Tea table'],
  ['piano', 'Piano'],
  ['flowers', 'Rose vase'],
  ['easel', 'Easel'],
  ['records', 'Record player'],
  ['trunk', 'Travel trunk'],
  ['lamp', 'Brass lamp'],
  ['plant', 'Fern'],
  ['table', 'Round table'],
  ['flowers', 'Orchids'],
  ['books', 'Low bookshelf'],
  ['desk', 'Oak desk'],
  ['trunk', 'Suitcase'],
  ['lamp', 'Reading lamp'],
  ['sofa', 'Armchair'],
];
